fishing:
  x: 1600
  y: 254
  width: 200
  height: 604
  timeouts:
    loop:
      min: 0.01
      max: 0.01
    notice:
      min: 1.5
      max: 2.0
    reeling:
      min: 0.7
      max: 1.7
    pause:
      min: 0.5
      max: 1.5
    cast:
      min: 1.6
      max: 1.8
repairing:
  x: 1600
  y: 860
  length: 25
  every: 2000
  enable: 1
  timeouts:
    arm_disarm:
      min: 1
      max: 1
    inventory:
      min: 1
      max: 1
    repair:
      min: 1
      max: 1
    confirm:
      min: 1
      max: 1
resolution:
  x: 5120
  y: 2160
log_lvl: INFO
