fishing:
  x: 1600
  y: 254
  width: 200
  height: 800
  timeouts:
    loop:
      min: 0.01
      max: 0.01
    notice:
      min: 1.5
      max: 2.0
    reeling:
      min: 0.7
      max: 1.7
    pause:
      min: 0.5
      max: 1.5
    cast:
      min: 1.6
      max: 1.8
repairing:
  x: 1600
  y: 860
  length: 25
  every: 2000
  enable: 1
  timeouts:
    arm_disarm:
      min: 1
      max: 1
    inventory:
      min: 1
      max: 1
    repair:
      min: 1
      max: 1
    confirm:
      min: 1
      max: 1
bait:
  bait_x: 2100
  bait_y: 780
  equip_button_x: 2380
  equip_button_y: 1100
  length: 25
  enable: 1
  timeouts:
    select:
      min: 0.1
      max: 1
    confirm:
      min: 0.1
      max: 1
colors:
  green:
    r: 14
    g: 191
    b: 140
  brown:
    r: 189
    g: 97
    b: 30
  red:
    r: 183
    g: 43
    b: 46
resolution:
  x: 5120
  y: 2160
log_lvl: INFO
